# Generated by Django 5.1.4 on 2025-01-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='Service',
        ),
    ]
